### ISSUE TITLE
Improve Trace Moe

### ISSUE THREAD

**Issue by arcadeena** [floorbot/floorbot#14]
- [x] anilistInfo should be an option
- [x] support /me endpoint
- [x] support api keys

**Comment by I-am-Stoney** [comment]
- [ ] add 18+ emote to hentai titles
- [ ] hentai videos should only be posted in NSFW channels
- [ ] Anilist button
- [ ] fix this link for stupid image stupid thing stupid patrick god he so stupid arc stupid too
https://cdn.discordapp.com/attachments/180194035976241152/917511110540804137/maxresdefault.png
Bonus movie link:
https://cdn.discordapp.com/attachments/180194035976241152/917552012156076092/silent-voice4.png
